### ISSUE TITLE
Group members incomplete

### ISSUE THREAD

**Issue by CDSFounder** [BNWEIN/CIPPAPIModule#14]
### Description

Hello,

I am unsure if this is an issue with the Powershell module or the CIPP API itself, but it does not appear that all groups members are returned. Specifically, we are using this to report on Distribution List members and have found that only 20 members in the "group" are shown, even though there are 80+.

For example, run a command like this:
$groups = Get-CIPPGroups -CustomerTenantID $company.tenantId 

Observe that the member count will not exceed 20
$group = $groups | Where-object {$_.mail -eq "example@example.com"}
$group.members.count

This is also true for the membersCsv result

### Environment data

```PowerShell
Module Version: 1.1.0
Back End Version: 6.0.0
```

**Comment by BNWEIN** [comment]
Good Morning. A few things

1: Can you update the module to the latest version? You are several versions behind
2:  This is a CIPP issue, rather than a module issue.  The same behaviour can be seen directly in CIPP. Both of the below groups have more than 20 members. Can you please raise a BUG report directly on https://github.com/KelvinTegelaar/CIPP/issues and someone will handle it.

![image](https://github.com/user-attachments/assets/1a8058e7-ef13-4c41-b92f-6ed219def8e7)
